"""
Generate a C++ lookup header from JSON maps (airline ICAO -> name, aircraft ICAO -> short name).

Usage:
  python tools/generate_lookup_header.py --airlines path/to/airlines.json --aircraft path/to/aircraft.json --out core/LookupTables.generated.h

The input JSON files should be flat objects, e.g.:
  { "AAL": "American Airlines", "DLH": "Lufthansa", ... }

The output header contains sorted arrays and count constants:
  static const LookupEntry kAirlineLookup[] = { ... };
  static constexpr size_t kAirlineLookup_COUNT = ...;
  static const LookupEntry kAircraftLookup[] = { ... };
  static constexpr size_t kAircraftLookup_COUNT = ...;
"""
import argparse
import json
from pathlib import Path


def sanitize_ascii(text: str) -> str:
    return text.encode("ascii", "ignore").decode("ascii")


def load_lookup(path: Path) -> dict[str, str]:
    with path.open("r", encoding="utf-8") as f:
        data = json.load(f)
    out = {}
    for k, v in data.items():
        key = str(k).strip().upper()
        val = sanitize_ascii(str(v).strip())
        if 3 <= len(key) <= 4 and val:
            out[key] = val
    return out


def emit_table(name: str, mapping: dict[str, str]) -> str:
    lines = [f"static const LookupEntry {name}[] = {{"]
    for code, val in sorted(mapping.items()):
        escaped = val.replace('"', r"\"")
        lines.append(f'    {{"{code}", "{escaped}"}},')
    lines.append("};")
    lines.append(f"static constexpr size_t {name}_COUNT = sizeof({name}) / sizeof({name}[0]);")
    return "\n".join(lines)


def main():
    parser = argparse.ArgumentParser(description="Generate lookup header from JSON maps.")
    parser.add_argument("--airlines", required=True, type=Path, help="Path to airlines.json")
    parser.add_argument("--aircraft", required=True, type=Path, help="Path to aircraft.json")
    parser.add_argument("--out", default=Path("core/LookupTables.generated.h"), type=Path, help="Output header path")
    args = parser.parse_args()

    airlines = load_lookup(args.airlines)
    aircraft = load_lookup(args.aircraft)

    header = [
        "// Auto-generated by tools/generate_lookup_header.py. Do not edit manually.",
        "#pragma once",
        "",
        "// lookup entry struct lives in FlightDataFetcher.cpp",
        "",
        emit_table("kAirlineLookup", airlines),
        "",
        emit_table("kAircraftLookup", aircraft),
        "",
    ]
    args.out.parent.mkdir(parents=True, exist_ok=True)
    args.out.write_text("\n".join(header), encoding="utf-8")
    print(f"Wrote {args.out} (airlines={len(airlines)}, aircraft={len(aircraft)})")


if __name__ == "__main__":
    main()
